version: '3'

services:
  tester:
    image: tester:depot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST_COURSE_SDK_PATH: "${PWD}"
    volumes:
      - .:/course-sdk
      - /var/run/docker.sock:/var/run/docker.sock