version: '3'

services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    environment:
      HOST_COURSE_SDK_PATH: "${PWD}"
    volumes:
      - .:/course-sdk
      - /var/run/docker.sock:/var/run/docker.sock