LANGUAGES = [
  Language.new(slug: "c", name: "C"),
  Language.new(slug: "cpp", name: "C++"),
  Language.new(slug: "clojure", name: "Clojure"),
  Language.new(slug: "crystal", name: "Crystal"),
  Language.new(slug: "csharp", name: "C#"),
  Language.new(slug: "elixir", name: "Elixir"),
  Language.new(slug: "go", name: "Go"),
  Language.new(slug: "haskell", name: "Haskell"),
  Language.new(slug: "java", name:"Java"),
  Language.new(slug: "javascript", name: "JavaScript"),
  Language.new(slug: "kotlin", name: "Kotlin"),
  Language.new(slug: "nim", name: "Nim"),
  Language.new(slug: "php", name: "PHP"),
  Language.new(slug: "python", name: "Python"),
  Language.new(slug: "ruby", name: "Ruby"),
  Language.new(slug: "rust", name: "Rust"),
  Language.new(slug: "swift", name: "Swift"),
]
